CREATE TABLE TRANSACTIONS(
COSTUMER_ID INT NOT NULL IDENTITY(100,1) PRIMARY KEY ,
AMOUNT DECIMAL(7,1),
PRODUCT VARCHAR(50),
PRODUCT_WEIGHT DECIMAL(5,2),
CREATED_DATE DATETIME,
MODIFIED_DATE DATETIME,
CREATED_BY VARCHAR(20)
);


INSERT INTO TRANSACTIONS
VALUES (223,'CHIPS',633,CURRENT_TIMESTAMP,NULL,NULL),
(250,'KIKIRITKI',998,CURRENT_TIMESTAMP,NULL,NULL),
(655,'JAJCA',455,CURRENT_TIMESTAMP,NULL,NULL),
(250,'MARGARIN',741,CURRENT_TIMESTAMP,NULL,NULL),
(452,'PAMUK',356,CURRENT_TIMESTAMP,NULL,NULL),
(698,'VINO BELO',175,CURRENT_TIMESTAMP,NULL,NULL),
(698,'VINO CRVENO',245,CURRENT_TIMESTAMP,NULL,NULL),
(864,'VINO ROZE',175,CURRENT_TIMESTAMP,NULL,NULL);


INSERT INTO TRANSACTIONS
VALUES(678,'CIPS',875,CURRENT_TIMESTAMP,NULL,NULL),
(856,'SMOKI',177,CURRENT_TIMESTAMP,NULL,NULL),
(452,'PEPSO',189,CURRENT_TIMESTAMP,NULL,NULL),
(224,'SINALCO',775,CURRENT_TIMESTAMP,NULL,NULL),
(665,'BRASHNO',295,CURRENT_TIMESTAMP,NULL,NULL),
(877,'MASLO',465,CURRENT_TIMESTAMP,NULL,NULL),
(765,'LOKUM',787,CURRENT_TIMESTAMP,NULL,NULL),
(756,'STOCK',224,CURRENT_TIMESTAMP,NULL,NULL),
(228,'VODKA',446,CURRENT_TIMESTAMP,NULL,NULL),
(864,'KONJAK',544,CURRENT_TIMESTAMP,NULL,NULL),
(234,'COCKTA',579,CURRENT_TIMESTAMP,NULL,NULL),
(446,'JAJCA',975,CURRENT_TIMESTAMP,NULL,NULL),
(156,'RIBI',664,CURRENT_TIMESTAMP,NULL,NULL),
(366,'PILESHKO MESO',889,CURRENT_TIMESTAMP,NULL,NULL),
(666,'SVINSKO MESO',744,CURRENT_TIMESTAMP,NULL,NULL),
(789,'TELESHKO MESO',500,CURRENT_TIMESTAMP,NULL,NULL),
(245,'KOKOSHKA',200,CURRENT_TIMESTAMP,NULL,NULL),
(444,'CHAJNA',105,CURRENT_TIMESTAMP,NULL,NULL),
(666,'SALAMA',35,CURRENT_TIMESTAMP,NULL,NULL),
(478,'LUT SOS',175,CURRENT_TIMESTAMP,NULL,NULL),
(520,'SLATKO-LUT SOS',175,CURRENT_TIMESTAMP,NULL,NULL),
(387,'DOMATI',90,CURRENT_TIMESTAMP,NULL,NULL),
(621,'PIPERKI',80,CURRENT_TIMESTAMP,NULL,NULL),
(639,'LUK',120,CURRENT_TIMESTAMP,NULL,NULL),
(165,'KROMID',122,CURRENT_TIMESTAMP,NULL,NULL),
(189,'CHAJ',55,CURRENT_TIMESTAMP,NULL,NULL),
(198,'NAPOLITANKI',110,CURRENT_TIMESTAMP,NULL,NULL),
(366,'BELO VINO',175,CURRENT_TIMESTAMP,NULL,NULL),
(784,'CRVENO VINO',175,CURRENT_TIMESTAMP,NULL,NULL),
(985,'KISELINA',478,CURRENT_TIMESTAMP,NULL,NULL),
(264,'VARIKINA',887,CURRENT_TIMESTAMP,NULL,NULL),
(142,'AJAX',225,CURRENT_TIMESTAMP,NULL,NULL),
(247,'TIKVA',669,CURRENT_TIMESTAMP,NULL,NULL),
(336,'LUBENICA',447,CURRENT_TIMESTAMP,NULL,NULL),
(368,'MISIRKA',788,CURRENT_TIMESTAMP,NULL,NULL),
(863,'PELISTERKA',889,CURRENT_TIMESTAMP,NULL,NULL);
UPDATE TRANSACTIONS
SET MODIFIED_DATE = CURRENT_TIMESTAMP, CREATED_BY = 'david'
WHERE AMOUNT < 300;
UPDATE TRANSACTIONS
SET CREATED_BY = 'N/A' 
WHERE CREATED_BY IS NULL;
SELECT * FROM TRANSACTIONS;

INSERT INTO TRANSACTIONS
VALUES(678,'CIPS',875,CURRENT_TIMESTAMP,NULL,NULL),
(856,'SMOKI',177,CURRENT_TIMESTAMP,NULL,NULL),
(452,'PEPSO',189,CURRENT_TIMESTAMP,NULL,NULL),
(224,'SINALCO',775,CURRENT_TIMESTAMP,NULL,NULL),
(665,'BRASHNO',295,CURRENT_TIMESTAMP,NULL,NULL),
(877,'MASLO',465,CURRENT_TIMESTAMP,NULL,NULL),
(765,'LOKUM',787,CURRENT_TIMESTAMP,NULL,NULL),
(756,'STOCK',224,CURRENT_TIMESTAMP,NULL,NULL),
(228,'VODKA',446,CURRENT_TIMESTAMP,NULL,NULL),
(864,'KONJAK',544,CURRENT_TIMESTAMP,NULL,NULL),
(234,'COCKTA',579,CURRENT_TIMESTAMP,NULL,NULL),
(446,'JAJCA',975,CURRENT_TIMESTAMP,NULL,NULL),
(156,'RIBI',664,CURRENT_TIMESTAMP,NULL,NULL),
(142,'AJAX',225,CURRENT_TIMESTAMP,NULL,NULL),
(247,'TIKVA',669,CURRENT_TIMESTAMP,NULL,NULL);

CREATE TABLE VEHICLES(
VEHICLE_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
PRICE DECIMAL(7,2),
VEHICLE_TYPE VARCHAR(50),
COLOR VARCHAR(4),
CREATED_DATE DATETIME,
MODIFIED_DATE DATETIME,
CREATED_BY VARCHAR(20)
);
SELECT * FROM VEHICLES;
INSERT INTO VEHICLES
VALUES(678,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(856,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(452,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(224,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(665,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(877,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(765,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(756,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(228,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(864,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(234,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(446,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(156,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(666,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(789,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(245,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(444,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(666,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(478,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(520,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(387,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(621,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(639,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(165,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(189,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(198,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(784,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(985,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(264,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(142,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(247,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(336,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(368,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(863,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL);

INSERT INTO VEHICLES
VALUES (639,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(165,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(189,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(198,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(784,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(985,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(264,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(142,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(247,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(336,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(368,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(863,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(765,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(756,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL);
UPDATE VEHICLES
SET MODIFIED_DATE = CURRENT_TIMESTAMP, CREATED_BY = 'david'
WHERE PRICE > 350;
UPDATE VEHICLES
SET CREATED_BY = 'N/A' 
WHERE CREATED_BY IS NULL;

SELECT * FROM VEHICLES;


CREATE TABLE OSIGURUVANJE(
OSIGURENIK_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
INSURANCE_PRICE DECIMAL(7,2),
INSURANCE_TYPE VARCHAR(50),
EXSITING_INSURANCE VARCHAR(3),
CREATED_DATE DATETIME,
MODIFIED_DATE DATETIME,
CREATED_BY VARCHAR(20)
);
INSERT INTO OSIGURUVANJE
VALUES (639,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(165,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(189,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(198,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(784,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(985,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(264,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(142,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(247,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(336,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(368,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(863,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(765,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(756,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(678,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(856,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(452,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(224,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(665,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(877,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(765,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(756,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(228,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(864,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(234,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(446,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(156,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(366,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(666,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(789,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(245,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(444,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(666,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(478,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(520,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(387,'LIGHT','NE',CURRENT_TIMESTAMP,NULL,NULL),
(621,'LIGHT','DA',CURRENT_TIMESTAMP,NULL,NULL),
(639,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(165,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(189,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(198,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(366,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(784,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(985,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL),
(264,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(142,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(247,'MEDIUM','NE',CURRENT_TIMESTAMP,NULL,NULL),
(336,'HARD','DA',CURRENT_TIMESTAMP,NULL,NULL),
(368,'HARD','NE',CURRENT_TIMESTAMP,NULL,NULL),
(863,'MEDIUM','DA',CURRENT_TIMESTAMP,NULL,NULL);
CREATE TABLE VEHICLES(
VEHICLE_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
PRICE DECIMAL(7,2),
VEHICLE_TYPE VARCHAR(50),
COLOR VARCHAR(4),
CREATED_DATE DATETIME,
MODIFIED_DATE DATETIME,
CREATED_BY VARCHAR(20)
);
INSERT INTO VEHICLES
VALUES(678,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(856,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(452,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(224,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(665,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(877,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(765,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(756,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(228,'LIMUSINE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(864,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(234,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(446,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(156,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(666,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(789,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(245,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(444,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(666,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(478,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(520,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(387,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(621,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(639,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(165,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(189,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(198,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(366,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(784,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(985,'HATCHBACK','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(264,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(142,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(247,'SEDANE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(336,'SEDANE','BELA',CURRENT_TIMESTAMP,NULL,NULL),
(368,'LIMUSINE','CRNA',CURRENT_TIMESTAMP,NULL,NULL),
(863,'HATCHBACK','BELA',CURRENT_TIMESTAMP,NULL,NULL);
UPDATE OSIGURUVANJE
SET MODIFIED_DATE = CURRENT_TIMESTAMP, CREATED_BY = 'david'
WHERE INSURANCE_PRICE < 800;
UPDATE OSIGURUVANJE
SET CREATED_BY = 'N/A' 
WHERE CREATED_BY IS NULL;
SELECT * FROM OSIGURUVANJE;

CREATE TABLE DOZVOLI(
KORISNIK_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
VOZACKA_DOZVOLA VARCHAR(2),
LICNA_KARTA VARCHAR(2),
PASSPORT VARCHAR(3),
CREATED_DATE DATETIME,
MODIFIED_DATE DATETIME,
CREATED_BY VARCHAR(20)
);




INSERT INTO DOZVOLI
VALUES('DA','NE','DA',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','NE',CURRENT_TIMESTAMP,NULL,NULL),
('NE','DA','DA',CURRENT_TIMESTAMP,NULL,NULL),
('DA','NE','NE',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','NE',CURRENT_TIMESTAMP,NULL,NULL),
('DA','NE','DA',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','NE',CURRENT_TIMESTAMP,NULL,NULL),
('DA','NE','NE',CURRENT_TIMESTAMP,NULL,NULL),
('NE','DA','DA',CURRENT_TIMESTAMP,NULL,NULL),
('NE','NE','NE',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','DA',CURRENT_TIMESTAMP,NULL,NULL),
('NE','DA','DA',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','NE',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','DA',CURRENT_TIMESTAMP,NULL,NULL),
('DA','DA','DA',CURRENT_TIMESTAMP,NULL,NULL);
UPDATE DOZVOLI
SET MODIFIED_DATE = CURRENT_TIMESTAMP, CREATED_BY = 'david'
WHERE PASSPORT = 'DA';
UPDATE DOZVOLI
SET CREATED_BY = 'N/A' 
WHERE CREATED_BY IS NULL;


ALTER TABLE VEHICLES
FOREIGN KEY (KORISNIK_ID) REFERENCES DOZVOLI(KORISNIK_ID);
ALTER TABLE VEHICLES
ADD KORISNIK_ID INT;
SELECT * FROM VEHICLES;

SELECT *  
FROM VEHICLES LEFT JOIN DOZVOLI
ON VEHICLES.KORISNIK_ID = DOZVOLI.KORISNIK_ID;

ALTER TABLE DOZVOLI
ADD CONSTRAINT FK_DOZVOLIRAB
FOREIGN KEY (RABOTNIK_ID) REFERENCES RABOTNICI(RABOTNIK_ID);



UPDATE DOZVOLI
SET RABOTNIK_ID = 1651
WHERE KORISNIK_ID = 51;
SELECT * FROM DOZVOLI;
ALTER TABLE DOZVOLI
DROP CONSTRAINT FK_DOZVOLIRAB;
SELECT * FROM DOZVOLI;

ALTER TABLE RABOTNICI ADD OSIGURENIK_ID INT;

UPDATE RABOTNICI
SET OSIGURENIK_ID = 51
WHERE RABOTNIK_ID = 1651;
SELECT * FROM RABOTNICI;

ALTER TABLE RABOTNICI
ADD CONSTRAINT FK_DOZVOLIOSG
FOREIGN KEY (OSIGURENIK_ID) REFERENCES OSIGURUVANJE(OSIGURENIK_ID);

ALTER TABLE OSIGURUVANJE ADD COSTUMER_ID INT;
SELECT * FROM TRANSACTIONS;

UPDATE OSIGURUVANJE
SET COSTUMER_ID = 214
WHERE OSIGURENIK_ID = 51;
SELECT * FROM OSIGURUVANJE;

ALTER TABLE OSIGURUVANJE
ADD CONSTRAINT FK_DOZVOLITRN
FOREIGN KEY (COSTUMER_ID) REFERENCES TRANSACTIONS(COSTUMER_ID);
SELECT *  
FROM RABOTNICI INNER JOIN OSIGURUVANJE
ON RABOTNICI.OSIGURENIK_ID = OSIGURUVANJE.OSIGURENIK_ID;
SELECT *  
FROM RABOTNICI LEFT JOIN OSIGURUVANJE
ON RABOTNICI.OSIGURENIK_ID = OSIGURUVANJE.OSIGURENIK_ID;
SELECT *  
FROM RABOTNICI RIGHT JOIN OSIGURUVANJE
ON RABOTNICI.OSIGURENIK_ID = OSIGURUVANJE.OSIGURENIK_ID;
SELECT *  
FROM RABOTNICI FULL JOIN OSIGURUVANJE
ON RABOTNICI.OSIGURENIK_ID = OSIGURUVANJE.OSIGURENIK_ID;

SELECT *  
FROM OSIGURUVANJE INNER JOIN TRANSACTIONS
ON OSIGURUVANJE.COSTUMER_ID = TRANSACTIONS.COSTUMER_ID;
SELECT *  
FROM OSIGURUVANJE LEFT JOIN TRANSACTIONS
ON OSIGURUVANJE.COSTUMER_ID = TRANSACTIONS.COSTUMER_ID;
SELECT *  
FROM OSIGURUVANJE RIGHT JOIN TRANSACTIONS
ON OSIGURUVANJE.COSTUMER_ID = TRANSACTIONS.COSTUMER_ID;

SELECT *  
FROM OSIGURUVANJE FULL JOIN TRANSACTIONS
ON OSIGURUVANJE.COSTUMER_ID = TRANSACTIONS.COSTUMER_ID;

EXEC sp_rename 'RABOTNICI', 'EMPLOYEES';
 sp_rename 'INSURANCE.OSIGURENIK_ID', 'ID', 'COLUMN';
  sp_rename 'LICENCES.LICNA_KARTA', 'IDENTITY_CARD', 'COLUMN';

  ALTER TABLE VEHICLES ALTER COLUMN COLOR VARCHAR (7);
UPDATE VEHICLES
SET COLOR = 'WHITE'
WHERE COLOR = 'BELA';
UPDATE VEHICLES
SET COLOR = 'BLACK'
WHERE COLOR = 'CRNA';

  sp_rename 'LICENCES.KORISNIK_ID', 'USER_ID', 'COLUMN';
  sp_rename 'LICENCES.RABOTNIK_ID', 'EMPLOYEE_ID', 'COLUMN';

  sp_rename 'INSURANCE.COSTUMER_ID', 'EMPLOYEE_ID', 'COLUMN';

ALTER TABLE INSURANCE
DROP CONSTRAINT FK_DOZVOLITRN;

ALTER TABLE INSURANCE
ADD CONSTRAINT FK_INSTOEMPL
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
UPDATE INSURANCE
SET EMPLOYEE_ID = 1648
WHERE EMPLOYEE_ID = 214;
SELECT * FROM INSURANCE;
ALTER TABLE TRANSACTIONS
ADD TRANSACTONS_ID INT;
ALTER TABLE TRANSACTIONS
DROP CONSTRAINT PK__TRANSACT__7E516B6B749A1A85;
sp_rename 'TRANSACTIONS.TRANSACTONS_ID', 'TRANSACTIONS_ID', 'COLUMN';

UPDATE TRANSACTIONS
SET TRANSACTIONS_ID = 222
WHERE COSTUMER_ID = 167;
ALTER TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTIONS_ID);
ALTER TABLE TRANSACTIONS
ALTER COLUMN TRANSACTIONS_ID INT NOT NULL;
ALTER TABLE TRANSACTIONS
DROP COLUMN TRANSACTIONS_ID;

ALTER TABLE TRANSACTIONS
ADD TRANSACTONS_ID INT ;


UPDATE TRANSACTIONS
SET TRANSACTIONS_ID = 929
WHERE COSTUMER_ID = 183;
ALTER TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTIONS_ID);
UPDATE table1 
    SET column1 = (
        SELECT column2
        FROM table2
        WHERE table2.id = table1.id
    );
sp_rename 'TRANSACTIONS.COSTUMER_ID', 'EMPLOYEE_ID', 'COLUMN';

UPDATE TRANSACTIONS
SET EMPLOYEE_ID = 1601
WHERE TRANSACTIONS_ID = 911;
ALTER TABLE TRANSACTIONS
DROP COLUMN EMPLOYEE_ID;
ALTER TABLE TRANSACTIONS
ADD EMPLOYEE_ID INT;

UPDATE TRANSACTIONS
SET EMPLOYEE_ID = 1651
WHERE TRANSACTIONS_ID = 961;

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_TRANSEMPLS
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);


sp_rename 'LICENCES.USER_ID', 'LICENCE_ID', 'COLUMN';

ALTER TABLE LICENCES
DROP CONSTRAINT FK_DOZVOLIRAB;

ALTER TABLE LICENCES
ADD CONSTRAINT PK_LICENEMPL
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);

sp_rename 'VEHICLES.USER_ID', 'LICENCE_ID', 'COLUMN';

ALTER TABLE VEHICLES
DROP CONSTRAINT FK_KORISNIK_ID;

ALTER TABLE VEHICLES
ADD CONSTRAINT FK_VEHICLLICEN
FOREIGN KEY (LICENCE_ID) REFERENCES LICENCES(LICENCE_ID);

ALTER TABLE VEHICLES
ADD PRIMARY KEY (VEHICLE_ID);
SELECT * FROM VEHICLES;


